#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

yabai -m config                                 \
    mouse_follows_focus          on             \
    focus_follows_mouse          autofocus      \
    window_origin_display        default        \
    window_placement             second_child   \
    window_shadow                on             \
    window_animation_duration    0.0            \
    window_opacity_duration      0.0            \
    active_window_opacity        1.0            \
    normal_window_opacity        0.95           \
    window_opacity               on             \
    insert_feedback_color        0xffd75f5f     \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 off            \
    top_padding                  10             \
    bottom_padding               10             \
    left_padding                 10             \
    right_padding                10             \
    window_gap                   06             \
    layout                       bsp            \
    mouse_modifier               fn             \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap


# space names
yabai -m space 1 --label "org"
yabai -m space 2 --label "www"
yabai -m space 3 --label "dev"
yabai -m space 4 --label "mail"
yabai -m space 5 --label "chat"
yabai -m space 6 --label "music"

# application excpetions
yabai -m rule --add app="^(AppCleaner|Garmin Express|GPG Keychain|Logi Options|Toggl Track|WeChat|YoudaoDict|Cisco Webex Meetings)$" manage=off
yabai -m rule --add app="^(System Settings|System Information|法语助手|EuDic)$" manage=off
yabai -m rule --add app="^(Zoom Workplace|zoom.us|EuDici|iTerm2)$" manage=off

# dialog boxes
yabai -m rule --add app="^Firefox$" title="^Opening .*$" manage=off

# apply the rules
yabai -m rule --apply 

# status bar
BAR_HEIGHT=30
yabai -m config external_bar all:$BAR_HEIGHT:0


echo "yabai configuration loaded.."
